# Generated by Django 4.1.2 on 2022-11-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd_familiares',
            name='edad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
