# Generated by Django 4.1.2 on 2022-11-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_alter_bd_familiares_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='bd_familiares2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='bd_familiares',
            name='fecha',
        ),
    ]
