# Generated by Django 4.1.2 on 2022-11-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_bd_familiares2_remove_bd_familiares_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bd_familiares2',
        ),
    ]
